drivers: input: fix -Wunused-but-set-variable errors
drivers/input/touchscreen/mediatek/focaltech_FT8720/focaltech_core.c:130:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
The local variable “ret” is written but never read, triggering -Werror,-Wunused-but-set param

(cherry picked from commit bc703319cf664ebe9b6f9430d95e56336e6ee899)
(cherry picked from commit fbe4d43f09c0c528d9410e91522341da7baeb7f3)