sound: aw87xxx: Remove unused variable 'profile' aw87xxx.c
error: variable 'profile' set but not used


Signed-off-by: Yudho Patrianto <kydh01123@gmail.com>