sound: soc: codecs: aw87xxx: remove unused variable \`acf_dde\`
kernel/xiaomi/fire/sound/soc/codecs/aw87xxx/aw87xxx_acf_bin.c:152:21: error: variable 'acf_dde' set but not used [-Werror,-Wunused-but-set-variable]
kernel/xiaomi/fire/sound/soc/codecs/aw87xxx/aw87xxx_acf_bin.c:284:31: error: variable 'acf_dde' set but not used [-Werror,-Wunused-but-set-variable]

Signed-off-by: Yudho Patrianto <kydh01123@gmail.com>